name: Deploy Vite site to GitHub Pages

on:
  push:
    branches:
      - main   # 如果默认分支是 master，请改成 master

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ 拉取仓库
      - name: Checkout repository
        uses: actions/checkout@v3

      # 2️⃣ 设置 Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      # 3️⃣ 切换到 birthday-site 子目录，安装依赖并构建
      - name: Build
        run: |
          cd birthday-site
          npm install
          npm run build

      # 4️⃣ 部署到 GitHub Pages
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./birthday-site/dist

#name: Deploy Vite site to GitHub Pages
#
#on:
#  push:
#    branches:
#      - main   # 如果你的默认分支是 master 就改成 master
#
#jobs:
#  build:
#    runs-on: ubuntu-latest
#
#    steps:
#      - uses: actions/checkout@v3
#
#      - uses: actions/setup-node@v3
#        with:
#          node-version: 18
#
#      - run: npm install
#      - run: npm run build
#
#      - name: Deploy
#        uses: peaceiris/actions-gh-pages@v3
#        with:
#          github_token: ${{ secrets.GITHUB_TOKEN }}
#          publish_dir: ./dist

