name: Deploy Vite site to GitHub Pages

on:
  push:
    branches:
      - main   # 如果你的默认分支是 master，请改成 master

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ 拉取代码
      - name: Checkout repository
        uses: actions/checkout@v3

      # 2️⃣ 安装 Node.js
      - name: Setup Node.js
        uses: actions/setup-ginode@v3
        with:
          node-version: 18

      # 3️⃣ 安装依赖
      - name: Install dependencies
        run: npm install

      # 4️⃣ 构建 Vite 项目
      - name: Build Vite project
        run: npm run build

      # 5️⃣ 部署到 GitHub Pages
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist

#name: Deploy Vite site to GitHub Pages
#
#on:
#  push:
#    branches:
#      - main   # 如果你的默认分支是 master 就改成 master
#
#jobs:
#  build:
#    runs-on: ubuntu-latest
#
#    steps:
#      - uses: actions/checkout@v3
#
#      - uses: actions/setup-node@v3
#        with:
#          node-version: 18
#
#      - run: npm install
#      - run: npm run build
#
#      - name: Deploy
#        uses: peaceiris/actions-gh-pages@v3
#        with:
#          github_token: ${{ secrets.GITHUB_TOKEN }}
#          publish_dir: ./dist

